### ISSUE TITLE
AttributeError: module 'scripts.resize_youtube' has no attribute 'resize_all'

### ISSUE THREAD

**Issue by RogerQi** [hkchengrex/XMem#10]
Hello - I tried to set up datasets to reproduce training results, but I got the following error when I run `scripts/download_datasets.py`

```
Extracting YouTube datasets...
Cleaning up YouTubeVOS datasets...
Resizing YouTubeVOS to 480p...
Traceback (most recent call last):
  File "scripts/download_datasets.py", line 115, in <module>
    resize_youtube.resize_all('../YouTube/train', '../YouTube/train_480p')
AttributeError: module 'scripts.resize_youtube' has no attribute 'resize_all'
```

I took a look at `scripts/resize_youtube.py`, and there does not seem to be a definition of function `resize_all`.

**Comment by RogerQi** [comment]
I pushed a commit that fixes the mentioned issue. I tested it on my local machine.

**Comment by hkchengrex** [comment]
Thanks, but I would like to keep it consistent with STCN.
