### ISSUE TITLE
[Question] A video longer than 1h

### ISSUE THREAD

**Issue by K-Maehashi** [hkchengrex/XMem#102]
Hi, I'm interested in using your method for animal detection.
The paper tests "three videos with more than 7,000 frames". Does this mean that we cannot use it for a long video (e.g. a video longer than 1h)?
Object detection is a quite new field for me and I would appreciate your help.

**Comment by hkchengrex** [comment]
Technically it can handle videos of unlimited length. Depending on the complexity of the video, the results may or may not become unreliable after 1h.
