### ISSUE TITLE
The dataset used in stage03

### ISSUE THREAD

**Issue by zht8506** [hkchengrex/XMem#109]
I found that validating the davis2017 results requires the use of youtube data, and I'm wondering which data exactly? I used youtube2018-train.zip but only get 85.5 JF  (vs 86.2 in your paper) on davis2017？ Do I need to use youtube2018-train_all_frames.zip or youtube2019-train.zip? Thank you very much.

**Comment by 1334233852** [comment]
I tested my own dataset, why didn't there be JF printing，thank you

**Comment by hkchengrex** [comment]
We used DAVIS 2017 train + YouTubeVOS 2019 train following standard practices.

**Comment by zht8506** [comment]
Thank you for your reply, it addresses my query very well.

**Comment by 1334233852** [comment]
> It needs to be validated separately to get the metrics, and no validation will be done during training.

Do you mean to write a separate Python file for validation metrics, which is not included in the source code? Sorry, I am a novice and asked these questions.

**Comment by hkchengrex** [comment]
You can use the tools listed here: https://github.com/hkchengrex/XMem/blob/main/docs/INFERENCE.md#getting-quantitative-results
