### ISSUE TITLE
Long-Time Video Tools

### ISSUE THREAD

**Issue by z-jiaming** [hkchengrex/XMem#113]
When getting quantitative results on Long-Time Video, we follow the [INFERENCE](https://github.com/hkchengrex/XMem/blob/main/docs/INFERENCE.md).md to use [davis2017-evaluation](https://github.com/davisvideochallenge/davis2017-evaluation)

We first point --davis_path to long_video_davis or long_video_davis_x3, then remove [resolution](https://github.com/davisvideochallenge/davis2017-evaluation/blob/ac7c43fca936f9722837b7fbd337d284ba37004b/davis2017/davis.py#L31) 

But raise error as follow:
<img width="1016" alt="image" src="https://github.com/hkchengrex/XMem/assets/42411674/256b1d94-b666-4cff-ac41-8148436e26dd">

Could you please help me to fix this bug, or directly provide your fixed tools?
Thanks a lot!

**Comment by hkchengrex** [comment]
It should work without any "fixes" to the tool. For debugging, I would recommend printing out the path to the file that it is trying to read and figuring out why it failed to read that file.

**Comment by z-jiaming** [comment]
I print "self.sequences[sequence][obj_type]" in self._get_all_elements(sequence, 'mask').
It looks like many "-1", due to "masks.extend([-1] * (len(images) - len(masks)))" in def __init__()

<img width="1640" alt="image" src="https://github.com/hkchengrex/XMem/assets/42411674/78ce59be-0797-4766-a5ae-a1baf20a95d7">


I simply filter out "-1", 
<img width="598" alt="image" src="https://github.com/hkchengrex/XMem/assets/42411674/fab4cdc0-0a05-4945-89b0-e9b4d86520ca">

but it also raises an error:
<img width="1203" alt="image" src="https://github.com/hkchengrex/XMem/assets/42411674/8962125a-521b-4335-a39b-6d48a93d0eb1">


Could you please directly provide your fixed tools?
It will help a lot!

**Comment by z-jiaming** [comment]
I eval results along the following steps:

1) Download Long-Time Video datasets from [[here]](https://drive.google.com/uc?id=100MxAuV0_UL20ca5c-5CNpqQ5QYPDSoz) which provided in GETTING_STARTED.md, and unzip like:
<img width="297" alt="image" src="https://github.com/hkchengrex/XMem/assets/42411674/5428e8eb-9e07-4ae4-aed0-fa7bf7b1c6a2">

2) Download your [[Precomputed Results]](https://drive.google.com/drive/folders/1NADcetigH6d83mUvyb2rH4VVjwFA76Lh?usp=sharing) and unzip like:
<img width="356" alt="image" src="https://github.com/hkchengrex/XMem/assets/42411674/eb47bc57-68ad-4a14-a34a-c5dc881bd033">
And delete your provided csv.

3) git clone [davis2017-evaluation](https://github.com/davisvideochallenge/davis2017-evaluation), fix img and mask directories as:
<img width="957" alt="image" src="https://github.com/hkchengrex/XMem/assets/42411674/5880efaf-d9d6-473d-a696-b5afbc4a9834">

4) eval as follows:
eval: `python evaluation_method.py --davis_path xxx/long_video_set/long_video --task semi-supervised --results_path xxx/LongVideo-1X-r10`
eval 3X: `python evaluation_method.py --davis_path xxx/long_video_set/long_video_x3 --task semi-supervised --results_path xxx/LongTime-3X-r10`

Then, raise the above errors.

Could you please help me to find where is wrong.

**Comment by hkchengrex** [comment]
1. You don't need the "fix" the directories as mentioned above.
2. In your post, you mentioned that you "point --davis_path to long_video_davis". The command that you have shown does not.

**Comment by z-jiaming** [comment]
1. I fix the directories due to DAVIS has 480p and Full-resolution, but LongTimeVideo not
2. I set davis_path as `--davis_path xxx/long_video_set/long_video_x3`

**Comment by hkchengrex** [comment]
How about you revert (1) and follow (2) as mentioned in our documentation? :)

**Comment by z-jiaming** [comment]
Oh, I know it, my mistake!
Thanks a lot!!!!
