### ISSUE TITLE
Make a custom dataset

### ISSUE THREAD

**Issue by wang-shuaikang** [hkchengrex/XMem#114]
Hello,
Thank you for your great work. I want to make a dataset by myself. Do I need to provide a video and the mask of the first frame of the video, and then according to which code in the project can I generate my object mask dataset? ? Can it be generated through the interactive_demo.py file? I would be very grateful if you could answer! ! !

**Comment by hkchengrex** [comment]
Using `eval.py` with https://github.com/hkchengrex/XMem/blob/main/docs/INFERENCE.md#on-custom-data should be the easiest way. You would need the mask of the first frame.
