### ISSUE TITLE
How is the mask of the first frame made？

### ISSUE THREAD

**Issue by wang-shuaikang** [hkchengrex/XMem#116]

**Comment by hkchengrex** [comment]
Can you be more specific?

**Comment by wang-shuaikang** [comment]
> Can you be more specific?
Hello, there are rgb files and annotation files in the input data format required by the XMem project, but the annotation file can be the first frame, so how can I get the annotation of the first frame when inputting the rgb file, and add the first frame Add the annotation of one frame to the annotation file, then use the rgb file and the annotation file of only the first frame to generate the annotation file of the next frame, and obtain the binary mask file of each frame

**Comment by hkchengrex** [comment]
That depends on your application. You can use our GUI tool for manual annotation.

**Comment by wang-shuaikang** [comment]
> That depends on your application. You can use our GUI tool for manual annotation.

ok
