### ISSUE TITLE
您能像stcn那样提供多尺度融合的代码吗？

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/XMem#117]
您能像stcn那样提供多尺度融合的代码吗？包括生成不同尺度中间结果的代码以及将多尺度融合的代码，如果能你的项目将非常完美了。
@hkchengrex 

![image](https://github.com/hkchengrex/XMem/assets/40291722/548e006e-bbc8-429c-9e26-1ca5a9bb01f0)

**Comment by longmalongma** [comment]
![image](https://github.com/hkchengrex/XMem/assets/40291722/64e1502f-c214-4e32-832c-ce83ad420176)
如何生成这种中间结果，谢谢

**Comment by hkchengrex** [comment]
It has always been here: https://github.com/hkchengrex/XMem/blob/main/docs/INFERENCE.md#multi-scale-evaluation

**Comment by longmalongma** [comment]
Thanks! Your work is very perfect!
