### ISSUE TITLE
Inference strategy

### ISSUE THREAD

**Issue by Amshaker** [hkchengrex/XMem#118]
Hello,

Thank you for your awesome work, I have a question regarding the inference strategy, please.

You mentioned in the paper that the training is based on a sequence of 8 frames.

During inference, what are the criteria? are you doing segmentation for every 8 consecutive frames? Please clarify the inference strategy.

**Comment by hkchengrex** [comment]
The model is online and always processes frame-by-frame. The 8-frame limit during training is only for resources/implementation consideration.
During inference, we process the entire video frame-by-frame (no reason not to).

**Comment by Amshaker** [comment]
Thanks for you reply.
