### ISSUE TITLE
Can I train in Windows enviroment?

### ISSUE THREAD

**Issue by returnlsz** [hkchengrex/XMem#119]
I notice that you test your code in Ubuntu,but I have built it in Windows.
So when I start training it cause the error:
RuntimeError: Distributed package doesn't have NCCL built in
Windows doesnt support nccl,but if I modify it to gloo can it work?
`import os
os.environ["PL_TORCH_DISTRIBUTED_BACKEND"] = "gloo"`
I will be very appreciated if you could answer and solve it.

**Comment by hkchengrex** [comment]
If PyTorch does not complain, it should be fine.

**Comment by returnlsz** [comment]
> If PyTorch does not complain, it should be fine.

It seems Windows still doesnt support.I wonder what Ubuntu Version is suit for this work

**Comment by hkchengrex** [comment]
All recent ones should work.
