### ISSUE TITLE
Operating platform

### ISSUE THREAD

**Issue by mjw123bs** [hkchengrex/XMem#12]
Hi,  @hkchengrex , I recently read the corresponding article on the code and think it is a great job. I see that you just tested the GUI on Windows and the code tested on Ubuntu, so can you debug the code on Windows as well?
Looking forward to your reply！

**Comment by Sazoji** [comment]
The GUI seems fully-functional on windows when using anaconda to set up the requirements, I've been playing around with the overlay modes to enable a layer sequence without issues on windows 11.

**Comment by mjw123bs** [comment]
> The GUI seems fully-functional on windows when using anaconda to set up the requirements, I've been playing around with the overlay modes to enable a layer sequence without issues on windows 11.

OK，Thanks! I'll try it.
