### ISSUE TITLE
About Training Testing Gap

### ISSUE THREAD

**Issue by yyang181** [hkchengrex/XMem#122]
Hi, I noticed that, during the training process, a memory bank is constructed by randomly selecting three frames from the input video consisting of eight frames. Notably, the ground truth (GT) values, instead of the model's predicted values, are stored in the memory bank. Could you elucidate the reasons behind the incongruity between the training and testing logic？

**Comment by hkchengrex** [comment]
We do use the model's predicted value in the memory bank. See https://github.com/hkchengrex/XMem/blob/4589acce67dfd952b28f779f9e55a39ce8ebb9d6/model/trainer.py#L111-L113
