### ISSUE TITLE
Dynamic Memory

### ISSUE THREAD

**Issue by abdksyed** [hkchengrex/XMem#123]
@hkchengrex 

Hello Rex, did you have a chance to try dynamic memory, like instead of adding the features every $r^{th}$ frame, add dynamically on some criteria? 

If yes, were there any performance improvements?

**Comment by hkchengrex** [comment]
There are papers about this but I haven't tried.

**Comment by abdksyed** [comment]
I did try to find them but couldn't get hold on any. If you don't mind can you share some papers regarding the dynamic memory?

**Comment by hkchengrex** [comment]
This is one: https://arxiv.org/abs/2207.07922
There are probably more.
