### ISSUE TITLE
how can I come accross this issue???

### ISSUE THREAD

**Issue by Aimeeman** [hkchengrex/XMem#125]
![image](https://github.com/hkchengrex/XMem/assets/55201552/2936399b-d661-4d89-89f9-ea97ffbe5af3)
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, wayland, linuxfb, offscreen, vnc, minimal, minimalegl, vkkhrdisplay, wayland-egl, eglfs.

**Comment by hkchengrex** [comment]
Not sure.
Here are some google results:
https://github.com/NVlabs/instant-ngp/discussions/300
https://stackoverflow.com/questions/68036484/qt6-qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-thou
