### ISSUE TITLE
Processing videos in batches

### ISSUE THREAD

**Issue by WangYixuan12** [hkchengrex/XMem#129]
Hi Rex, thank you for the amazing work! I am using XMem for multi-view VOS. Currently, I create multiple processors and process videos in series. I am wondering whether it is possible to take in multiple videos as batches and process them in parallel to speed up. Thank you for your help!

**Comment by WangYixuan12** [comment]
I guess a more concrete question is whether [step function](https://github.com/hkchengrex/XMem/blob/9ea04795564dcff06b6570132aed7eedba94d9b8/inference/inference_core.py#L42C24-L42C24) can take in images in batch

**Comment by hkchengrex** [comment]
Thank you for your interest. 

This is not implemented. As a side note, [Cutie](https://github.com/hkchengrex/Cutie) would probably run faster and better.

**Comment by WangYixuan12** [comment]
Thank you for your reply! Do you have any quantitative comparisons between Cutie and XMem? I notice that XMem has ~20FPS. What is the expected FPS for Cutie?

**Comment by hkchengrex** [comment]
Paper: https://arxiv.org/abs/2310.12982
Around 35. FPS depends on the resolution/the number of objects just like XMem.
