### ISSUE TITLE
Why should similarity scores be normalized? What if it is not normalized?

### ISSUE THREAD

**Issue by xinbaiw** [hkchengrex/XMem#130]
Why should similarity scores be normalized? What if it is not normalized?

![image](https://github.com/hkchengrex/XMem/assets/143494439/48259c41-242f-4a07-b100-9721dfcc1635)

**Comment by hkchengrex** [comment]
Because we want a probability, not the sum.

**Comment by xinbaiw** [comment]
Thank you for your reply. Can you explain more specifically? I didn't understand. The similarity score needs to be multiplied by the value of memory. Does non normalization have any impact?

**Comment by hkchengrex** [comment]
This is not the same normalization that you asked about in https://github.com/hkchengrex/STCN/issues/151#issuecomment-1791821712. This is to compute the usage of each element. Without normalization, the algorithm would dispositionally favor old elements.

**Comment by xinbaiw** [comment]
Ok, thank you very much!
