### ISSUE TITLE
A simple question!Thanks

### ISSUE THREAD

**Issue by 1334233852** [hkchengrex/XMem#131]
Thank you for your code and hard work！I have a simple question，batch_size = 8,The input data dimension accepted by KeyEncoder is BxCxHxW (before flattening, it was BxCxTxHxW), and I trained with two GPUs. Is BxCxTxHxW equal to [4,3,3384384]? Do I understand correctly? Thank you!

**Comment by hkchengrex** [comment]
In pre-training, yes.

**Comment by 1334233852** [comment]
sorry sorry ，i missed a comma....  lol   I remember that the main training seems to be the same, right?
