### ISSUE TITLE
When I'm working on a folder of images, frames are always skipping, in random order, and some frames keep repeating.

### ISSUE THREAD

**Issue by Wahaha-code** [hkchengrex/XMem#133]
When I'm working on a folder of images, frames are always skipping, in random order, and some frames keep repeating.

**Comment by hkchengrex** [comment]
We use `sort` to order the frames. Are the names of the images sortable?

**Comment by hkchengrex** [comment]
Closed due to inactivity. Feel free to re-open if there are any updates.
