### ISSUE TITLE
XMem trained on MOSE

### ISSUE THREAD

**Issue by Vujas-Eteph** [hkchengrex/XMem#141]
Hi there 👋,

I've been following your works with great interest! 
I recently read the Cutie paper and noted that you reported results of an XMem variant trained with the MOSE dataset. I'm currently using XMem in my project. However, I haven't been able to find the specific [weights](https://github.com/hkchengrex/XMem/releases/tag/v1.0) of XMem trained on MOSE within the repository. Would it be possible for you to provide access to those weights?

Your support would be greatly appreciated!

Cheers!

**Comment by hkchengrex** [comment]
added

**Comment by Vujas-Eteph** [comment]
Thanks !
