### ISSUE TITLE
Codes of generating Long-term memory key

### ISSUE THREAD

**Issue by JiaxingChai** [hkchengrex/XMem#143]
i haven't found any codes of the "Prototype Selection", "Memory Potentiation", "Removing Obsolete Features" algorithms mentioned in your paper

**Comment by hkchengrex** [comment]
https://github.com/hkchengrex/XMem/blob/a4427dbd748f66ed8fef159b529527e23060c666/inference/memory_manager.py#L211

https://github.com/hkchengrex/XMem/blob/a4427dbd748f66ed8fef159b529527e23060c666/inference/memory_manager.py#L243

https://github.com/hkchengrex/XMem/blob/a4427dbd748f66ed8fef159b529527e23060c666/inference/memory_manager.py#L187
