### ISSUE TITLE
The problem of computational complexity of models

### ISSUE THREAD

**Issue by Heisenberggggggg** [hkchengrex/XMem#144]
Thank you very much for your work and contributions in the field of video object segmentation. May I ask how to obtain the computational complexity of the model? thank you

**Comment by hkchengrex** [comment]
With respect to what? Strictly speaking, it is O(1) with respect to video length, and O(n^2) with respect to the number of pixels in a frame.

**Comment by Heisenberggggggg** [comment]
不好意思，我可能没说清楚，是模型的计算复杂度（FLOPs）  lol....

**Comment by Heisenberggggggg** [comment]
您好您好！再次打扰！我在trainer.py的do_pass方法里面添加了代码用于计算四个模块（encode_key/encode_value/read_memory/segment）的参数量和FLOPs，前两个模块都能正确获取这两个参数，但是后面两个模块一直出现问题，我试了很多方法都没有得到解决，是不是我参数传的不太正确，希望您指点一二！感谢！下面是错误截图
![19D1A8E3EA74ABF8F3BE02A72AE2A83A](https://github.com/user-attachments/assets/c1369725-cf4b-404f-8399-dd6ed3025524)
![BAB20A24E2B4A59ACD1522838BD67981](https://github.com/user-attachments/assets/c8849276-c900-47dd-a1c6-016531b519f9)
下面是添加的代码截图（trainer.py的do_pass方法中）
![1F588EC143E2A7097B559727B31B394C](https://github.com/user-attachments/assets/8353c3ae-5261-4983-90a3-0a8ba4914f58)
![504104098A1E2E4EC13EBFD16AFB9065](https://github.com/user-attachments/assets/a805336d-a194-4050-b088-8e586ae2405e)
期待您的回复！

**Comment by hkchengrex** [comment]
Hi, 

I don't know which package you are using to compute the FLOPs. You can always start from the first principle -- they are mostly just basic operations like mat-mul/scaling/conv/etc.

**Comment by Heisenberggggggg** [comment]
感谢您的回复！ 我想问这里的read_memory模块参数量为0，FLOPs也是0正常吗，应该不对吧？我还是想请问，我如何从第一准则开始呢？不是很理解，感谢您！

**Comment by hkchengrex** [comment]
1. If by `read_memory`, you mean this function https://github.com/hkchengrex/XMem/blob/a4427dbd748f66ed8fef159b529527e23060c666/model/network.py#L89
then it has no parameters. Models (objects) carry the parameter. Functions do not.
It should not have a 0-FLOP.

2. What you measure is what you get. I do not know how to answer this question without knowing what you want to obtain.

**Comment by Heisenberggggggg** [comment]
非常感谢您的回复！受益匪浅，我再认真看一看！祝您生活愉快！
