### ISSUE TITLE
Model XMem getting stuck at `nn.init.orthogonal_`

### ISSUE THREAD

**Issue by abdksyed** [hkchengrex/XMem#148]
I am using some modified version of eval.py, when I trying to initialize the XMem model via `network = XMem(config, args.model).cuda().eval()`, I see that inside XMem, we first do `init_hyperparameters` to get hyper-parameters value from passed model weights file. 

After that, we initialize different modules, during this initialize many times, it is getting stuck at initializing `self.key_proj = KeyProjection(1024, self.key_dim)`. I added print statements before and after every line to check and finally came across the issue that the code is stuck at https://github.com/hkchengrex/XMem/blob/a4427dbd748f66ed8fef159b529527e23060c666/model/modules.py#L204

Any idea as to why this is happening? This doesn't happen when I am finetuning the model, but only when I am doing testing. I tried removing `.eval()`, but no use. I even tried without passing `args.model` when initializing and passing the model_weights using `load_weights` function, but it is getting stuck at initialization itself.

Did you face any such issue before, or any help would be appreciated.

**Comment by hkchengrex** [comment]
Hi, thank you for raising the issue. I haven't encountered this before, and I am surprised that it is stuck there --orthogonal init should be a fairly simple function with little room for errors.

Could you run `nn.init.orthogonal_` independently? Like
```python
import torch
conv = torch.nn.Conv2d(64, 64, 3)
nn.init.orthogonal_(conv.weight.data)
```

**Comment by abdksyed** [comment]
This works fine for me. To avoid this, whenever I am passing model weights, the weights files will have all the weights, so I am not doing init when passing file. This avoid any init when fine-tuning and testing.

Will try to dig deeper on why this keeps happening, and get back here in future

**Comment by yufeiyg** [comment]
Hi, I'm having the same issue, have you fixed it?
