### ISSUE TITLE
Details of "config"

### ISSUE THREAD

**Issue by eneserdo** [hkchengrex/XMem#15]
Thanks for the great work! Could you explained the meanings of these parameters?

```
    config = {
        'top_k': 30,
        'mem_every': 5,
        'deep_update_every': -1,
        'enable_long_term': True,
        'enable_long_term_count_usage': True,
        'num_prototypes': 128,
        'min_mid_term_frames': 5,
        'max_mid_term_frames': 10,
        'max_long_term_elements': 10000,
    }
```

**Comment by hkchengrex** [comment]
The "help" in the argument parser of `eval.py` should give you some idea. Some of those rely on the description in the paper. Feel free to comment if you find any of them still unclear.

**Comment by hkchengrex** [comment]
Closed due to inactivity.

**Comment by liruiw** [comment]
Hi, thanks for the great repo. When I tried to use it for some real world single-object tracking in hand with initialization from Segment-Anything, i realized that it can under segment quite a bit, i.e. it can lose track of objects. I wonder if any of these configs can potentially decrease the segmentation threshold a bit? Or do you recommend other methods? Thanks again

**Comment by hkchengrex** [comment]
@liruiw Hi. Unfortunately, there is no such threshold. Tracking performance might be improved in general by increasing both `max_mid_term_frames` and `min_mid_term_frames` (say increasing from 10/5 to 30/25).

**Comment by liruiw** [comment]
Thanks for the reply. I assume the new work https://arxiv.org/pdf/2309.03903.pdf would work better for tracking a single object under occlusions and fast motions?

**Comment by hkchengrex** [comment]
That's what we observe from all the benchmarks. We do note that it does not perform as well for very long videos when we tried it in some in-the-wild examples -- it tends to shift its attention to other objects when the target object is missing (documented here https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/docs/EVALUATION.md).
This might not be a problem in your case. I definitely recommend you to try 😄.

**Comment by liruiw** [comment]
Thanks for the suggestion. In my setting, I would prefer to use the point prompt in SAM to initialize video segmentation. I assume [this](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/deva/ext/automatic_processor.py#L25)  is where i need to modify?

**Comment by hkchengrex** [comment]
@liruiw Let's move the discussion to https://github.com/hkchengrex/Tracking-Anything-with-DEVA.
