### ISSUE TITLE
Explanation about the object group

### ISSUE THREAD

**Issue by wangjk666** [hkchengrex/XMem#16]
Hi, thanks for your great work.

I feel a little bit confused about the usage of "object groups" in the working and long-term memory, and unfortunately, there is no explanation about it in the paper. Therefore, I wonder whether you could provide some clues? Thanks a lot.

**Comment by hkchengrex** [comment]
That is just one way for me to batch data together. Hope the comments in https://github.com/hkchengrex/XMem/blob/main/inference/kv_memory_store.py help.

**Comment by wangjk666** [comment]
Thanks for your reply. I'm not sure whether I understand the comments correctly. Does "Objects in the same group share the same temporal extent, i.e., objects initialized in the same frame are in the same group" means an object group contains the objects that appear for the first time in the upcoming frame? 

For VOS, we only need to segment the objects that appear in the first frame, right? I wonder why there can be multiple object groups for YouTubeVOS?

**Comment by hkchengrex** [comment]
The tricky thing is not all objects appear in the first frame for YouTubeVOS. If all objects appear in the first frame, you can disregard the notion of object groups.

**Comment by wangjk666** [comment]
But for VOS, we only need to segment the objects appearing in the first frame? (sorry I'm new to VOS...)

**Comment by hkchengrex** [comment]
That is just not true for YouTubeVOS. You can view their data and see it for yourself. The main reason is that not all objects are visible in the first frame and only come into view later. YouTubeVOS is a bit inconsistent (IMO) in when to label these objects. I basically divided the video into different "tracks" (each track contains a group of objects, hence "object group"). In each track, the objects appear in the first frame of that track.

**Comment by wangjk666** [comment]
Ok, I really appreciate your help.
