### ISSUE TITLE
VOS given mask in the middle of the sequence

### ISSUE THREAD

**Issue by jasonyzhang** [hkchengrex/XMem#19]
Thanks for the great work!

I have a video sequence in which I only have a ground truth segmentation for a frame in the middle of the sequence. What would be the correct way to propagate this mask both forward and backward?

Currently, when `first_mask_loaded` if False, I'm adding the frame back into the queue to re-process at the end. And I set end in `processor.step` to be True only when all of those frames are also processed. Is this the right way to do this?

**Comment by hkchengrex** [comment]
There can be multiple ways to do this and I am not sure which one is the best. Assuming the frame with annotation is indexed t, you can process them as 
1. t, t+1, t+2, ..., T, t-1, t-2, ..., 0
2. t, t-1, t-2, ..., 0, t+1, t+2, ..., T
3. t, t+1, t+2, ..., T, [clear memory bank], t, t-1, t-2, ..., 0
4. t, t+1, t-1, t+2, t-2, ..., T, 0
etc.

If you are appending to the end of the queue, that gives t, t+1, t+2, ..., T, 0, 1, 2, ..., t-1. I would guess this is similar to but a bit worse than (1).

I guess you would have to try to know which one is better for your task. Would have to know the result.

**Comment by jasonyzhang** [comment]
Thanks, that was really helpful! I'll probably use 1 or 3 to minimize complexity.
