### ISSUE TITLE
Playback frames not updated properly after propagation

### ISSUE THREAD

**Issue by bananajoe182** [hkchengrex/XMem#2]
Hi,
first of all great work, well done! 
While testing the interactive GUI (on Windows) I discovered some strange behavior after correcting a frame and propagating again.It seems that while propagating, the corrected frames are taken into account and the new propagated mask looks correct but once propagation is finished and I play it somehow shows the old cache from before propagating. If I close the gui and reopen it`s seems that the already existing masks are correct like they looked while propagating. Is there some kind of playback cache that is not updated correctly ? 
Hope this makes sense :)
Thanks!

**Comment by hkchengrex** [comment]
I have encountered that bug before and thought I have fixed it. Let me check. Thanks for reporting.

**Comment by hkchengrex** [comment]
Yes, it was a buffering problem. FIxed -- thanks.

**Comment by bananajoe182** [comment]
Thanks!
