### ISSUE TITLE
What's wrong with git？

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/XMem#20]
@hkchengrex What's wrong with git？How to install git?

![image](https://user-images.githubusercontent.com/40291722/185417602-f315ca11-4df2-419a-9cda-52da1d95d141.png)

**Comment by hkchengrex** [comment]
We log the git commit id in training. You need to clone the repo for it to properly read an id.

**Comment by longmalongma** [comment]
> We log the git commit id in training. You need to clone the repo for it to properly read an id.

Ok, thanks!
