### ISSUE TITLE
Intermediate ground truth mask for tracked objects

### ISSUE THREAD

**Issue by ShijieVVu** [hkchengrex/XMem#21]
Is there a way to provide intermediate ground truth mask for objects already in the memory to correct their drifting?

**Comment by hkchengrex** [comment]
For the GUI, it should be obviously doable.
For batch processing (eva.py), I haven't tried this but I think if you 
1. create your new test dataset (in `inference/data/test_datasets.py`), which feeds `use_all_mask=True` to `VideoReader` and
2. pass `exhaustive=True` to `mapper.convert_mask()` in `eval.py`.
, it should work.

If the drifting is severe, you might also want to flush the memory bank when a new frame is loaded. Let me know if it works.
