### ISSUE TITLE
Where is the "Working & Long-Time Memory" in the code? 

### ISSUE THREAD

**Issue by Haodayu** [hkchengrex/XMem#25]
It looks just randomly sampled from historical reference frames.

Is it not fully open source yet? Or does this simple strategy work well? 

Anyway, thanks for your work.

**Comment by hkchengrex** [comment]
You might be confusing training with inference. See https://github.com/hkchengrex/XMem/blob/main/inference/memory_manager.py

**Comment by Haodayu** [comment]
You're right. 

I ignored "We adopt the open-source implementation of STCN without modification" mentioned in the paper. Therefore, the Xmem mechanism is used during inference.

Amazing work, thanks!

**Comment by hkchengrex** [comment]
That quote is out of context. It is only valid for the static image deformation process. There are a few differences with STCN during training.

**Comment by Haodayu** [comment]
Yeah, I see. 
I also noticed that you retrained STCN under the same setting as Xmem. Such detailed experiments are rare. 
Thumbs up for you!
