### ISSUE TITLE
Save MemoryManager to disk

### ISSUE THREAD

**Issue by nick008a** [hkchengrex/XMem#29]
I would like to be able to pause when doing segmentation for a very long video.

Is it safe to save ``MemoryManager`` (https://github.com/hkchengrex/XMem/blob/main/inference/memory_manager.py) to disk as a `.pkl` on disk, and reload it later to continue on the next frame? Does it contain everything that is needed for the XMem?

**Comment by hkchengrex** [comment]
Hmmm I haven't tried that. Most likely you would need `torch.save` since it contains tensors. Saving `InferenceCore` might be another option.
