### ISSUE TITLE
A simple predict example?

### ISSUE THREAD

**Issue by binominerigike** [hkchengrex/XMem#3]
Hi, I'm trying to run this on a remote server, so the interactive demo.py isn't running for me.  
  
Do you have a simple script that takes in just 1 image, and outputs the result as another? 
  
I haven't put as much time into this as I would like to, but when I tried the normal model(input_img) using transforms to input a PIL image, I got the following:    
   
`RuntimeError: Given groups=1, weight of size [64, 6, 7, 7], expected input[1, 3, 3008, 2032] to have 6 channels, but got 3 channels instead`  
  
Do I need to resize the image? The size parameter is set to 480, so perhaps I will try that, though I would love to see how you would do that. Thanks for this project by the way, it looks amazing!

**Comment by hkchengrex** [comment]
The Colab demo (in the readme, https://colab.research.google.com/drive/1RXK5QsUo2-CnOiy5AOSjoZggPVHOPh1m?usp=sharing) can probably help you
