### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by nomorecoding** [hkchengrex/XMem#30]
Hi~ I'm using this repo to test my custom video, but get CUDA out of memory error. The resolution of my video is 4k, video length is 60s at 25FPS. Which settings could I change to make it possible to run this excellent work? Many thanks~~

**Comment by hkchengrex** [comment]
XMem scales well to long video but unfortunately not to high-resolution. The easiest way is to infer at a lower resolution and upsample the masks after.

**Comment by bfan1256** [comment]
Hi, has anyone detected if this loses any data / output performance during the downsample and upsampling process. We're working with 1920x1080 and want to scale to use 4K data.  I'd suspect this wouldn't scale too well...
