### ISSUE TITLE
Interactive demo and models on Hugging Face

### ISSUE THREAD

**Issue by NimaBoscarino** [hkchengrex/XMem#31]
Hello! First of all – thank you for open sourcing your work, and congrats on being accepted to ECCV 2022!

Would you be interested in porting the interactive demo over to [Hugging Face Spaces](https://hf.space)? We have documentation for [creating Spaces](https://huggingface.co/docs/hub/spaces), but I'm also more than happy to help you out if it's something you're interested in. I could even put in a request to get a GPU assigned to your demo for the conference.

The pretrained models could also be hosted for free on Hugging Face, where our users could find them! ([Docs for this](https://huggingface.co/docs/hub/models-uploading)) Beyond making models discoverable, putting models on the Hub makes it easier for users to build projects using your work – [like this Space someone released today that's built on top of 3 models](https://huggingface.co/spaces/ysharma/Talk_to_Multilingual_AI_WhisperBloomCoqui) 👀 

Let me know if you're interested, and if there's anything that I can do to help. And enjoy ECCV 2022!

cc: @osanseviero

**Comment by hkchengrex** [comment]
Hi, thanks for the invite! Would definitely be interested once I have some more free time :smile:

**Comment by NimaBoscarino** [comment]
Sounds great! Feel free to reach out anytime, we'd love to help out 😊
