### ISSUE TITLE
Number of GPUs

### ISSUE THREAD

**Issue by yk-pku** [hkchengrex/XMem#34]
Hi, I wonder the default number of GPU is 2? If I want to train the s012 model in stage 2 with the pretrained model s01 on 1 GPU, then I need to change the s2_batch_size to 16 rather than the default 8??

**Comment by hkchengrex** [comment]
You don't have to change anything. The code would adjust such that the total effective batch size is the same.

**Comment by yk-pku** [comment]
Thanks! Please feel free to close this issue
