### ISSUE TITLE
Question about single object and multiple objects training

### ISSUE THREAD

**Issue by wjn922** [hkchengrex/XMem#37]
Hello, thanks for your wonderful project!

I notice that the codebase supports single object and multiple objects training. I wonder if there is a performance gap between the two training strategies? Thank you!

**Comment by hkchengrex** [comment]
Single object training is only used for static image pre-training which only consists of one object mask. We always use multi-object training whenever possible.

**Comment by wjn922** [comment]
Got it. Thanks.

**Comment by j-merz** [comment]
Related to this question: If training was only done on single objects, will the model perform poorly for occlusions when it is used with multiple objects during inference?
