### ISSUE TITLE
How to segment my own datasets?

### ISSUE THREAD

**Issue by glode515** [hkchengrex/XMem#4]
How can I segment my image or video?

**Comment by hkchengrex** [comment]
Does this help: https://github.com/hkchengrex/XMem/blob/main/docs/INFERENCE.md?

**Comment by glode515** [comment]
I found eval.py can only infer specific datasets, such as "16/D17/Y18/Y19/LV1/LV3/G"

**Comment by hkchengrex** [comment]
Did you see the "On custom data" section?

**Comment by mjw123bs** [comment]
If I want to train my own dataset, do I need to set up the datasets in it according to [GETTING_STARTED.md](url)?

**Comment by hkchengrex** [comment]
@mjw123bs If you are not going to use them then no.

**Comment by mjw123bs** [comment]
> @mjw123bs If you are not going to use them then no.

ok thanks, i'll try it.

**Comment by mjw123bs** [comment]
> @mjw123bs If you are not going to use them then no.

Hi, I have some problems, how to train on custom data with a single gpu? And in the "on custom data" section, is .png a mask? Is video1 the original video?

**Comment by hkchengrex** [comment]
@mjw123bs 

1. I don't know how is your data formatted. I imagine you can copy/paste/edit some of our loading code in `train.py` and `dataset/vos_dataset.py`.
2. Yes. Like DAVIS/YouTubeVOS.

**Comment by mjw123bs** [comment]
> 

Thanks for the quick reply！ I'll try it.

**Comment by Eliza-wxq** [comment]
> > 
> 
> Thanks for the quick reply！ I'll try it.

Could you please tell me whether you have successfully deployed? Train your own data set on a single GPU.

**Comment by mjw123bs** [comment]
> > > 
> > 
> > 
> > Thanks for the quick reply！ I'll try it.
> 
> Could you please tell me whether you have successfully deployed? Train your own data set on a single GPU.

Sorry, no, I haven't done any research since then. I will inform you as soon as I get the results.

**Comment by Eliza-wxq** [comment]
> 

Thank you very much for your quick reply
