### ISSUE TITLE
GPU Out-Of-Memory and step function

### ISSUE THREAD

**Issue by Davidyao99** [hkchengrex/XMem#42]
Hello, I am trying to work with the XMem code base and I wanted to check my understanding of the step function, particularly the valid_labels parameter. From reading the code, it seems that the valid_labels contain the labels that are present in the ground truth mask? I suppose this is so that we can add in ground truth masks only covering a subset of all currently tracked labels by the mode?

Additionally, when running the model I run into cuda out-of-memory issue after around frame 100. I was wondering which parameter should I adjust in my memory so as to cap the total GPU memory usage so that the program does not crash. 

Thank you!!

**Comment by hkchengrex** [comment]
1. Yes. That is needed for YouTubeVOS.
2. Shouldn't happen for normal videos with mid-end GPUs. Is it high-resolution/does it has a lot of objects or something else?

**Comment by Davidyao99** [comment]
I see, thank you! I managed to resolve the issue by lowering the resolution of my images and rescaling them up later on. My video was of dimensions 1920x1080 and I have thousands of frames.
