### ISSUE TITLE
Is the environment of xmem the same as that of stcn? 

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/XMem#46]
Is the environment of xmem the same as that of stcn? Why can't the environment of stcn run xmem on the same machine?

**Comment by hkchengrex** [comment]
The environment is listed here: https://github.com/hkchengrex/XMem/blob/main/docs/GETTING_STARTED.md

Most of them are the same except PyTorch. I usually see the latest version of PyTorch for development. Some of the newer features are not supported by the old PyTorch version used in STCN.

**Comment by longmalongma** [comment]
> The environment is listed here: https://github.com/hkchengrex/XMem/blob/main/docs/GETTING_STARTED.md
> 
> Most of them are the same except PyTorch. I usually use the latest version of PyTorch for development. Some of the newer features are not supported by the old PyTorch version used in STCN.

但是我使用同样的机器也要更新pytorch版本吗？
