### ISSUE TITLE
Where can I find the memory encoding of the first frame when testing?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/XMem#48]
Where can I find the memory encoding of the first frame when testing?
@hkchengrex

**Comment by longmalongma** [comment]
> 测试时在哪里可以找到第一帧的内存编码？ @hkchengrex

which lline?

**Comment by hkchengrex** [comment]
https://github.com/hkchengrex/XMem/blob/139a7458b84a4829cb3bc7434cea1e7383eca5f8/eval.py#L206

https://github.com/hkchengrex/XMem/blob/139a7458b84a4829cb3bc7434cea1e7383eca5f8/inference/inference_core.py#L96-L101
