### ISSUE TITLE
--size flag does not change the size of the output images in interactive_demo.py 

### ISSUE THREAD

**Issue by andrewyguo** [hkchengrex/XMem#49]
I am trying to run through `interactive_demo.py` but I noticed that the size of the output images remains at 480 x 640 even if I set `--size -1` or `--size 1440`. The original dimensions of my input video is `1440x1920`. 

My input is a video. 

This this expected behaviour?

**Comment by hkchengrex** [comment]
No.
It might have cached the resized images from a previous run in the workspace. Can you delete the workspace and try again?

**Comment by andrewyguo** [comment]
Thank you! 

Deleting the workspace containing the images and masks worked for me.
