### ISSUE TITLE
GUI collapse!!!

### ISSUE THREAD

**Issue by codylcs** [hkchengrex/XMem#5]
hi,thanks for your great work!
when i run interactivate to show 147 imgs, GUI always collapse when runing about 40th imgs:
so why not release GPU MEM ?
![image](https://user-images.githubusercontent.com/48380363/179910863-0576c0c9-a70d-46ca-a0ee-edad3a503831.png)

**Comment by hkchengrex** [comment]
It appears to me that you are using a much larger image size (not recommended...)
Other than that, 
1. You might have other programs occupying GPU memory. That is shown by the first bar but not the second bar.
2. Caching is managed by PyTorch. I trust that they do a good job and therefore there might actually be not enough free memory left to work with. See (1). You might want to check `nvidia-smi` and the OOM error when it crashed.

**Comment by codylcs** [comment]
> It appears to me that you are using a much larger image size (not recommended...) Other than that,
> 
> 1. You might have other programs occupying GPU memory. That is shown by the first bar but not the second bar.
> 2. Caching is managed by PyTorch. I trust that they do a good job and therefore there might actually be not enough free memory left to work with. See (1). You might want to check `nvidia-smi` and the OOM error when it crashed.

hi,i check it again, 
as u say:_It appears to me that you are using a much larger image size_
when img_size is 1920*1080, it always collapsed;but here i change img size to 1280*720, it can run wonderfully!!
but how to run with normal resolution like 1080p or higher resolution?
here i paste to imgs to show GPU MEM usage;
![image](https://user-images.githubusercontent.com/48380363/179921659-7bab561c-a390-4637-92ae-e53056993b95.png)


![image](https://user-images.githubusercontent.com/48380363/179921287-1bec8c00-bfbf-483c-80c6-8748c8aa1c89.png)

**Comment by hkchengrex** [comment]
While XMem scales well to long videos, it unfortunately does not scale well to high resolution. The simplest way is to keep using a lower resolution and upsample the mask in a later stage.
The GPU memory usage looks fine. I am not exactly sure why it is crashing this early... One possibility is that the GPU usage in the GUI is only updated every 2 seconds and the program might have used more memory within those two seconds.

**Comment by codylcs** [comment]
thank for your reply ,nice work,shou dong dian zan!!!
