### ISSUE TITLE
The result out of domain

### ISSUE THREAD

**Issue by xwhkkk** [hkchengrex/XMem#57]
Hello !  thanks for sharing your great job!

I noticed your model also achieved a promising result in an out-of-domain case. Have you tested your model's performance in other domains, e.g. infrared images? And how about the robustness of your model in the out-of-domain case?

Thank you !

**Comment by hkchengrex** [comment]
I don't think it would work on infrared images. That example is just an interesting case. I have not extensively tested its robustness in different domains.

**Comment by xwhkkk** [comment]
> I don't think it would work on infrared images. That example is just an interesting case. I have not extensively tested its robustness in different domains.

Thanks for your kind reply !
