### ISSUE TITLE
About the best result

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/XMem#58]
" main training at 107K iterations leads to the best result (full training is 110K). "(see https://github.com/hkchengrex/XMem/blob/main/docs/TRAINING.md) Which training process is this sentence refer to, s012 or s03? The iterations of main training is 150K in s2 and 100K in s3 in your code, neither of which is 110K.

**Comment by hkchengrex** [comment]
You need to add the 10K iterations for finetuning.
https://github.com/hkchengrex/XMem/blob/139a7458b84a4829cb3bc7434cea1e7383eca5f8/util/configuration.py#L73
