### ISSUE TITLE
The accuracy is lower than that in the paper

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/XMem#60]
I used the default parameters in the code, first used two 2080ti to train s0, then used two v100 to train s3, and tested the results of 100K-110k iterations. The best result of Davis 2017 val was 85.3% (at 110K), which is lower than what you wrote in the paper (86.2). Do you know what caused this result?

**Comment by hkchengrex** [comment]
I trained it five times with default parameters at that time and have never gotten below 86.0 J&F on DAVIS 2017. 
1. How about performances on other datasets? Have you tried disabling AMP (with `--benchmark`)?
2. What are your training commands?

**Comment by zhouweii234** [comment]
1. The accuracy of YT18 is 85.3, slightly lower than your result. 
2. I haven't tried disabling AMP. Thanks for the suggestion, I'll give it a try.
3. I first use `CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.run --master_port 25763 --nproc_per_node=2 train.py --exp_id retrain --stage 03` to train on 2 2080Ti, but it reports `CUDA out of memory` after finish s0. So I train the s3 on 2 v100 using `CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.run --master_port 25763 --nproc_per_node=2 train.py --exp_id retrain --stage 3 --load_network ./saves/Jan06_03.30.21_retrain_s0_150000.pth`.
4.  Is it possible that this result is caused by the fact that I used two 2080Ti to train s0? Since you use two RTX A6000 to train the network.

**Comment by hkchengrex** [comment]
(I meant disabling AMP during testing, not training)
PyTorch training should supposedly give close-to-device-agnostic results, so it shouldn't matter which GPU you are training on. From experience, that's not always the case though. If nothing else works, you can try training both stages on V100s in a single command.

**Comment by hkchengrex** [comment]
Continue in #71.
