### ISSUE TITLE
GUI demo，--num_objects Cannot enter a number greater than 10

### ISSUE THREAD

**Issue by hlcool** [hkchengrex/XMem#61]
When executing “python interactive_demo.py --video [path to the video] --num_objects 15” commands，You can only enter 9 at most through the keyboard，Both 0 and 1 are entered and cannot be recognized as 10

**Comment by hkchengrex** [comment]
True that the GUI not expecting >9 objects. You can bind new keys for those objects here: https://github.com/hkchengrex/XMem/blob/139a7458b84a4829cb3bc7434cea1e7383eca5f8/inference/interact/gui.py#L330

**Comment by hlcool** [comment]
3Q, great job
