### ISSUE TITLE
Query - Custom Mask

### ISSUE THREAD

**Issue by arnavmehta7** [hkchengrex/XMem#64]
Hey, is it possible to use a custom mask for inference? Let's say I draw a grayscale object mask, and now I want to feed it to the model to generate tracked area of the whole video... I want to do it in a single script, I have written the code, but I'm confused in the pallete part, the numbers in length of objects are not correct. Can someone please explain me the pallete part?

**Comment by arnavmehta7** [comment]
EDIT: I figured it out and it's working, but when I draw a mask on my own and put pallete on it, I see that on boundaries the put_pallete automatically adds more colors, due to which the number of objects increase even though it is in reality not.

**Comment by arnavmehta7** [comment]
![image](https://user-images.githubusercontent.com/65492948/219879753-910cec29-99eb-4d6e-adf7-04910382c0ac.png)
Like here

**Comment by hkchengrex** [comment]
Hi, this seems to be a rather common question so I added some documentation here: https://github.com/hkchengrex/XMem/blob/main/docs/PALETTE.md

Most likely your mask has smoothed edges.

**Comment by arnavmehta7** [comment]
@hkchengrex Thanks for a fast response, I had been just using a scribble tool and creating the mask from it in colored and then put the pallete over it.
```colored_mask =  Image.fromarray(cv2.cvtColor(mask, cv2.COLOR_BGR2RGBA).astype(np.uint8)).convert('P')

colored_mask.putpalette(pal)```
when I just save above colored_mask then it show's me above image as in screenshot. Could this be a problem with opencv?

**Comment by hkchengrex** [comment]
What is the shape and content of `mask`?

**Comment by arnavmehta7** [comment]
I think the shape is:
(X,Y, 3) 

The mask is just a image that contains the ROI in a colored form

**Comment by hkchengrex** [comment]
Probably better to first convert it to grayscale: `mask = mask.mean(-1)`, then check if the mask does not have smoothing: `print(np.unique(mask))`

**Comment by arnavmehta7** [comment]
![image](https://user-images.githubusercontent.com/65492948/219922417-0f80c4ca-db4d-410d-999e-1e5b217cffb6.png)

I tried that, but still final saved pallete is in above form, the edges not clean 😞. What are the ways to solve this? Could there be any way that I could specify how many colors there will be in final palleted image?

```
mask = cv2.imread(os.path.join('base_dir', 'canvas.png'))
colored_mask =  Image.fromarray(cv2.cvtColor(mask, cv2.COLOR_BGR2GRAY).astype(np.uint8)).convert('P')
colored_mask.putpalette(pal)

**Comment by arnavmehta7** [comment]
My end goal is to supply a custom mask and make it work in the colab notebook.

**Comment by hkchengrex** [comment]
Can you provide `print(np.unique(mask))` for debugging?

**Comment by arnavmehta7** [comment]
`print(np.unique(mask))` ->`[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]` 

I annotate the image like this
![image](https://user-images.githubusercontent.com/65492948/219922907-e85b4283-0339-48a7-b553-89b84472088b.png)

When I tried to convert the mask itself to Gray:
![canvas](https://user-images.githubusercontent.com/65492948/219922943-e54dde42-a85d-44ae-80ec-ba8636ac7934.png)


When I put the pallete it becomes:
![palletted](https://user-images.githubusercontent.com/65492948/219922993-3d497d50-066c-4d22-bb32-9eddf3264b42.png)

**Comment by hkchengrex** [comment]
`print(np.unique(mask)) ->[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]`

That's the problem! Why would there be so many different values in the mask? To solve this we need to learn which of these to keep/discard.

**Comment by arnavmehta7** [comment]
Yeah that is, how can I solve this 🤔

**Comment by hkchengrex** [comment]
So where does this mask come from (like which function)? What is the expected output from that function?

**Comment by hkchengrex** [comment]
Like 'file.png' -- how did you obtain that?

**Comment by arnavmehta7** [comment]
Mask comes like this:
```
            img = canvas_result.image_data.copy()
            img[np.where(img[:, :, 3] == 0)] = (0, 0, 0, 255)
            cv2.imwrite(os.path.join(st.session_state['base_dir'], 'canvas.png'), cv2.cvtColor(img, cv2.COLOR_BGR2GRAY))
```

**Comment by hkchengrex** [comment]
And what would `canvas_result.image_data` be?

**Comment by arnavmehta7** [comment]
it will be a numpy array representing image

**Comment by hkchengrex** [comment]
No, like where does that data come from

**Comment by arnavmehta7** [comment]
streamlit canvas 
```
canvas_result = st_canvas(
        fill_color="#9B002C",  # Fixed fill color with some opacity
        stroke_color=stroke_color,
        stroke_width=stroke_width,
        background_image=Image.fromarray(st.session_state['image']),
        update_streamlit=True,
        drawing_mode="freedraw",
        display_toolbar=True,
        key="canvas")

```

**Comment by hkchengrex** [comment]
`st_canvas` probably has built-in smoothing. I briefly looked at their API and there seems to be no way to disable it. 

A hacky way to fix it would be to change your code to:
```
mask = cv2.imread(os.path.join('base_dir', 'canvas.png'))
mask = cv2.cvtColor(mask, cv2.COLOR_BGR2GRAY)
mask = (mask>0).astype(np.uint8)
colored_mask =  Image.fromarray(mask).convert('P')
colored_mask.putpalette(pal)
```

This however would not work for multiple objects.

**Comment by arnavmehta7** [comment]
I am fine to even make it work for 1 object. Lemme just implement your changes and get back to you.

**Comment by arnavmehta7** [comment]
Wow, Thankyou so much!

**Comment by arnavmehta7** [comment]
`Objects:  [0 1]`
It's fine for 1 object now. 

So conclusion is that the streamlit API is not good, so if I make it work with a custom written website, then it should be working fine. Correct?

**Comment by hkchengrex** [comment]
I am not familiar with streamlit so I am not sure whether there is actually no way to disable smoothing. Any tools that produce masks with discrete edges should work well.

Happy to see it working. If you don't mind, it would be great for you to post the later finished notebook here for others' reference. I also have a colab demo but I didn't implement drawing 😄

**Comment by arnavmehta7** [comment]
Yes, I will make a repo and post the streamlit code  :)

**Comment by arnavmehta7** [comment]
https://github.com/arnavmehta7/XMem/tree/streamlit

here is the code that has the streamlit code available. I've updated the required files. Very easy to setup. Hopefully later on, I'll create a react-site do it with multiple objects at a time. The speed of running it insane. Insanely fast.
