### ISSUE TITLE
When to use the long-term memory

### ISSUE THREAD

**Issue by xwhkkk** [hkchengrex/XMem#66]
Hello, thanks for sharing your great work! I checked the code in the part of `trainer.py` and did not include " load long-term memory'. Besides, I found long-term memory in the `memory_manager.py`. Does it mean the training stage only uses working memory? and long-term memory only used in the test/eval stage?

**Comment by hkchengrex** [comment]
Yes; there are no trainable parameters in the long-term memory

**Comment by xwhkkk** [comment]
> Yes; there are no trainable parameters in the long-term memory

Thanks for your kind reply. When to engage the long-term memory during eval stage ? In the default config to evaluate DAVIS17, I  noticed the long-term would been engaged  when the number of frames in working memory is 9. Is it an initialization setting ?

**Comment by xwhkkk** [comment]
> > Yes; there are no trainable parameters in the long-term memory
> 
> Thanks for your kind reply. When to engage the long-term memory during eval stage ? In the default config to evaluate DAVIS17, I noticed the long-term would been engaged when the number of frames in working memory is 9. Is it an initialization setting ?

> > Yes; there are no trainable parameters in the long-term memory
> 
> Thanks for your kind reply. When to engage the long-term memory during eval stage ? In the default config to evaluate DAVIS17, I noticed the long-term would been engaged when the number of frames in working memory is 9. Is it an initialization setting ?

I figured it out. Sorry for my misunderstanding.
