### ISSUE TITLE
About the overall performance?

### ISSUE THREAD

**Issue by David-19940718** [hkchengrex/XMem#7]
Congrats and thank you for such a great job. How does this model perform in segmentation with multiple target objects (assuming their motion is relatively smooth)? Also, does its runtime increase with more objects?

**Comment by hkchengrex** [comment]
1. You can check the benchmark results here: https://github.com/hkchengrex/XMem/blob/main/docs/RESULTS.md (DAVIS 2017 and YouTubeVOS are both multi-object). One of the demo videos is also multi-object.
2. Yes. It has a constant cost for image processing plus a linear cost (per object) for mask processing.
