### ISSUE TITLE
如果我用四个gpu训练，batch size是不是得减半？

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/XMem#70]
您好，请问如果我用四个gpu训练，batch是不是得减半？
![image](https://user-images.githubusercontent.com/40291722/223946299-36f951f3-e2e3-47b9-bed8-37de5635d79e.png)

**Comment by longmalongma** [comment]
![image](https://user-images.githubusercontent.com/40291722/223946492-d94c20d2-4f86-4a5b-bc6e-db8f1e75a399.png)

**Comment by longmalongma** [comment]
我是用这个命令训练的：
CUDA_VISIBLE_DEVICES=0,1,2,3 OMP_NUM_THREADS=64 python -m torch.distributed.launch --master_port 2313 --nproc_per_node=4 train.py --exp_id xmemnopre --stage 2 --benchmark
@hkchengrex

**Comment by xwhkkk** [comment]
> 我是用这个命令训练的： CUDA_VISIBLE_DEVICES=0,1,2,3 OMP_NUM_THREADS=64 python -m torch.distributed.launch --master_port 2313 --nproc_per_node=4 train.py --exp_id xmemnopre --stage 2 --benchmark @hkchengrex

Hello. I also used the 4 gpu to train stage2. I think we do not need to change anything. Please see #34

**Comment by longmalongma** [comment]
> not

感谢您的回复，但是奇怪的是我用不同的4 gpus训练分别是4卡3080ti和4卡2080ti，为啥训练速度是一模一样？但之前训stcn的时候这两个机器的速度相差是很大的。

**Comment by 1334233852** [comment]
同学你好，我想问一下如果用自己的数据集训练并且测试的话，有什么细节吗？感谢感谢

**Comment by firrice** [comment]
> > not
> 
> 感谢您的回复，但是奇怪的是我用不同的4 gpus训练分别是4卡3080ti和4卡2080ti，为啥训练速度是一模一样？但之前训stcn的时候这两个机器的速度相差是很大的。@hkchengrex @xwhkkk

因为batchsize是总的batchsize而不是单卡的，总的训练时间由 batchsize和iterations这两个因素决定，因此你用四卡还是两卡，并不影响这两个因素的值（单卡的3080虽然略优于2080，但4卡的通信成本略高于双卡）一低一高，最后的结果就是差不多
