### ISSUE TITLE
Have you tried using only use Deep update or Per-frame update?

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/XMem#74]
Have you tried using only use Deep update or Per-frame update?

**Comment by zhouweii234** [comment]
Sorry, I noticed that you tried not to use Deep update in Table 8, have you tried using only use Deep update?

**Comment by hkchengrex** [comment]
The "Every single frame" in Table 8 means that we apply deep update every frame. It's not exactly "only use deep update" but it's close.

**Comment by hkchengrex** [comment]
Not that I am aware of.
