### ISSUE TITLE
May I ask the interpolation frequency you use when using STCN on Long-time Video dataset？

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/XMem#75]
I set `--mem_every` to 10, and I set the max size of memory to 50 frames, since it always reports `cuda out of memory`. The result is 99.7, but it takes three hours for inference on one V100, which is too long. May I ask your settings for STCN on Long-time Video dataset?

**Comment by hkchengrex** [comment]
Does this answer your question: https://github.com/hkchengrex/XMem/issues/73#issuecomment-1487520086?

For XMem, we only need to change `mem_every` to 10 and nothing else.

**Comment by zhouweii234** [comment]
Thank you for the quick answer!

So you set the` --mem_every` parameter in `eval_generic.py` in the `STCN` code to` 5`, and keep the maximum number of memory frames in the `MemoryBank` not exceeding `50`. The `STCN` using this configuration can achieve about `87.3% J&F` on  Long-time Video (1×), right?

However, I set the` --mem_every` parameter in `eval_generic.py` in the `STCN` code to` 10`, and also keep the maximum number of memory frames in the `MemoryBank` not exceeding `50`. The `STCN` using this configuration can achieve about `99.8% J&F` (99.8% J&F, 99.5%J, 100%F) on Long-time Video (1×).
I used the code you provided (obtained from the URL https://github.com/hkchengrex/STCN), and used the stcn_s03.pth pre-trained model (from the URL https://drive.google.com/file/d/ 1JllXPJZola0G-g1aUQfXe9nLMBioj-aH/view download). 
For keeping the maximum number of memory frames in the `MemoryBank` not exceeding `50`, I adjusted the `add_memory()` function in `class MemoryBank` in `inference_memory_bank.py` as following:

    def add_memory(self, key, value, is_temp=False):
        # Temp is for "last frame"
        # Not always used
        # But can always be flushed
        self.temp_k = None
        self.temp_v = None
        key = key.flatten(start_dim=2)
        value = value.flatten(start_dim=2)

        if self.mem_k is None:
            # First frame, just shove it in
            self.mem_k = key
            self.mem_v = value
            self.CK = key.shape[1]
            self.CV = value.shape[1]
            self.len = key.shape[2]
        else:
            if is_temp:
                self.temp_k = key
                self.temp_v = value
            else:
                maxlen = 50 # max total memory frames
                if self.mem_k.shape[2] >= self.len*maxlen:
                    self.mem_k = torch.cat([self.mem_k[:,:,:self.len], key], 2)
                    self.mem_v = torch.cat([self.mem_v[:,:,:self.len], value], 2)
                else:
                    self.mem_k = torch.cat([self.mem_k, key], 2)
                    self.mem_v = torch.cat([self.mem_v, value], 2)

I don't think just modifying insertion frequency from 5 to 10 would make such a big difference in performance
**(99.8% J&F in my experiment VS 87.3% J&F in your paper)**
Is there anything else in my configuration that is different from yours (except insertion frequency)?

**Comment by hkchengrex** [comment]
I don't think 99.8% J&F is achievable... You might want to ensure that STCN is not loading all the ground-truth masks. For example, you can delete all the masks except the first one in the folder you feed to STCN.

**Comment by zhouweii234** [comment]
Thanks for your guide, it works!
