### ISSUE TITLE
ValueError: failed to initialize intent(inout) array -- expected elsize=8 but got 4

### ISSUE THREAD

**Issue by STAR-811** [hkchengrex/XMem#77]
Hi! Thank you for your excellent work!
But I met an error recently:
The input video contains 17 fish. And I type in the command: 'python interactive_demo.py --video ./video/17-fish_Trim_compress.avi  --num_objects 1' for GUI interaction. When I annotate (click) the first frame, it reports an error after I click 6 or 7 times to annotate the 7th fish.
The error is as below:
![image](https://user-images.githubusercontent.com/71710781/231039421-f4c85897-b680-4609-89a6-4ae76f5390d6.png)

I would appreciate it if you could help me.

**Comment by hkchengrex** [comment]
It looks like an internal error in f-BRS and I don't know what could have caused it. Can you try their GUI and see if you have the same problem https://github.com/SamsungLabs/fbrs_interactive_segmentation?

**Comment by STAR-811** [comment]
I tried the demo on your provided website and it didn't report this error. But the segmentation performance is much worse. Can I derive anything from this?

**Comment by STAR-811** [comment]
I find that when I use this GUI https://github.com/hkchengrex/MiVOS, it didn't report this error, either.

**Comment by STAR-811** [comment]
I wonder whether the segmentation performance in the first frame of MiVOS is almost the same as XMem? I used the same `fbrs.pth` and `s2m.pth` model file.

**Comment by STAR-811** [comment]
This problem has been solved. I tried `scribble` instead of `click`. 
![image](https://user-images.githubusercontent.com/53425563/231923794-e98d252c-d2bd-43ed-bcc9-ea56340b188a.png)
