### ISSUE TITLE
Problem about the stages of training

### ISSUE THREAD

**Issue by XiShen1989** [hkchengrex/XMem#79]
Hi, thanks for your excellent work!
I have some problems about the stages of training.I want to use the pretrained model, like Xmem-s012.pth, to train my own data(frames of a video) for fine-tuning, I set the training stage as 0, but met a error as:
**RuntimeError: Error(s) in loading state_dict for XMem:
	size mismatch for value_encoder.conv1.weight: copying a param with shape torch.Size([64, 5, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 4, 7, 7]).**
I don`t know whether my configuration is right.

**Comment by hkchengrex** [comment]
You can comment out this line if you want to finetune a trained model in stage 0: https://github.com/hkchengrex/XMem/blob/5fe108138d457774f91ace362ecf97b9491f81d9/train.py#L61

**Comment by XiShen1989** [comment]
Thank you for your reply！That really helps！Wish you a good day~
