### ISSUE TITLE
Not a directory: './test/Annotations/00001.jpg'

### ISSUE THREAD

**Issue by Cococyh** [hkchengrex/XMem#8]
Thank you for your excellent contribution, but I met some problems when testing with my own data.

I prepared the data set as you mentioned in your introduction:
XMem
           test
                Annotations
                                    00001.jpg
                JPEGImages
                                    00001.jpg
                                    00002.jpg

And I ran python eval.py --generic_path ./test --dataset G met error:

Output path not provided. Defaulting to ../output/G_val
save_all is forced to be true in generic evaluation mode.
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
Traceback (most recent call last):
  File "/home/ubuntu/cyh/XMem_fold/XMem/eval.py", line 148, in <module>
    for vid_reader in progressbar(meta_loader, max_value=len(meta_dataset), redirect_stdout=True):
  File "/home/ubuntu/miniconda3/envs/py39/lib/python3.9/site-packages/progressbar/shortcuts.py", line 10, in progressbar
    for result in progressbar(iterator):
  File "/home/ubuntu/miniconda3/envs/py39/lib/python3.9/site-packages/progressbar/bar.py", line 546, in __next__
    value = next(self._iterable)
  File "/home/ubuntu/cyh/XMem_fold/XMem/inference/data/test_datasets.py", line 22, in get_datasets
    name[:-4] for name in os.listdir(path.join(self.mask_dir, video))
NotADirectoryError: [Errno 20] Not a directory: './test/Annotations/00001.jpg'
100% (50 of 50) |############################################| Elapsed Time: 0:00:00 ETA:  00:00:00

I would be grateful if you could provide a response.

**Comment by hkchengrex** [comment]
Looks like the directory structure does not match the template. See https://github.com/hkchengrex/XMem/blob/main/docs/INFERENCE.md

**Comment by Cococyh** [comment]
Oh, I didn't notice there was a "video1" directory, thanks!
