### ISSUE TITLE
May I ask why you don't compare the FPS of your method with other methods in Table 1 on the Long-time Video dataset?

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/XMem#80]
May I ask why you don't compare the FPS of your method with other methods in Table 1 on the Long-time Video dataset?

**Comment by hkchengrex** [comment]
We highlight results that we think are the most important. There are some results on FPS in Fig. S7 (in the appendix). But note that the two STCNs are not the same (in Table 1 we change the memory frequency to fit in our memory constraints; in Fig. S7 we "use a high-capacity 32GB V100 GPU" to experiment without a memory constraint).
