### ISSUE TITLE
No Error, But GUI does't show up, with "This plugin does not support propagateSizeHints()"

### ISSUE THREAD

**Issue by ToniButland1998** [hkchengrex/XMem#81]
**The GUI doesn't appear, and it stuck at this stage. The terminal shows**"
Got keys from plugin meta data ("webp")
QFactoryLoader::QFactoryLoader() checking directory path "/home/xiaoyin/miniconda3/envs/py38/bin/imageformats" ...
loaded library "/home/xiaoyin/miniconda3/envs/py38/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqgif.so"
loaded library "/home/xiaoyin/miniconda3/envs/py38/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqicns.so"
loaded library "/home/xiaoyin/miniconda3/envs/py38/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqico.so"
loaded library "/home/xiaoyin/miniconda3/envs/py38/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqjpeg.so"
loaded library "/home/xiaoyin/miniconda3/envs/py38/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqsvg.so"
loaded library "/home/xiaoyin/miniconda3/envs/py38/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqtga.so"
loaded library "/home/xiaoyin/miniconda3/envs/py38/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqtiff.so"
loaded library "/home/xiaoyin/miniconda3/envs/py38/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqwbmp.so"
loaded library "/home/xiaoyin/miniconda3/envs/py38/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqwebp.so"
QFactoryLoader::QFactoryLoader() checking directory path "/home/xiaoyin/miniconda3/envs/py38/lib/python3.8/site-packages/PyQt5/Qt5/plugins/accessiblebridge" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/xiaoyin/miniconda3/envs/py38/bin/accessiblebridge" ...
**This plugin does not support propagateSizeHints()**
QFactoryLoader::QFactoryLoader() checking directory path "/home/xiaoyin/miniconda3/envs/py38/lib/python3.8/site-packages/PyQt5/Qt5/plugins/accessible" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/xiaoyin/miniconda3/envs/py38/bin/accessible" ...
"

Looks like the issue of PyQt5. I reinstalled it with" 
 pip3 install pyqt5
AND
 pip install pyqt5"

Still doesn't work.
this is my resullt of my" conda list | grep qtpyqt"        

![image](https://user-images.githubusercontent.com/42618317/232563161-92946e2d-4f52-45e7-9c36-e509551c198f.png)

**Comment by hkchengrex** [comment]
Can you run other PyQt applications? I have not encountered this.

**Comment by ToniButland1998** [comment]
> 

Thank you for your quick reply. what are the other pyqt app?

**Comment by hkchengrex** [comment]
Any other PyQt5 program. Something like this: https://pythonbasics.org/pyqt-hello-world/?

**Comment by ToniButland1998** [comment]
> Any other PyQt5 program. Something like this: https://pythonbasics.org/pyqt-hello-world/?

Thanks. I can't run hello-world with pyqt either. The terminal has the same output (output), but the window just can't show up.

**Comment by hkchengrex** [comment]
It seems like a generic problem with your setup which I think is best directed to other platforms like stackoverflow.

**Comment by ToniButland1998** [comment]
> It seems like a generic problem with your setup which I think is best directed to other platforms like stackoverflow.

Thank you for your quick reply. I will try to figure it out. I would come back to post solutions once I found it.
