### ISSUE TITLE
Low speed when I train the model by 8 GPUs

### ISSUE THREAD

**Issue by Qi-Zhangyang** [hkchengrex/XMem#82]
I use 8 GPUs in total and set the batch size to 8. But the speed is too slow(slower than use 1 GPUs). What is the problem?

**Comment by hkchengrex** [comment]
There are many possible reasons e.g., your inter-GPU communication is slow, or your CPUs are not catching up. Unfortunately, it is almost impossible for me to debug performance-related problems remotely.
