### ISSUE TITLE
Training too slow

### ISSUE THREAD

**Issue by jingliang95** [hkchengrex/XMem#90]
Thanks for your work.

When I train your model in S0, it takes around 100 hours to finish. I think I meet a data loading problem as the gpu usage is not high. When I disable calling TPS, the required time reduces to 48 hours, which are still a lot. I tried to increase num_workers and OMP_NUM_THREADS, bit it did not help much. I am using ubuntu and 2 A10G gpus with 23G memory.

Could you help?

**Comment by hkchengrex** [comment]
Your CPU might be too slow.

**Comment by jingliang95** [comment]
Hi, it is a little strange. Actually, I am using AWS G5 instances: https://aws.amazon.com/blogs/aws/new-ec2-instances-g5-with-nvidia-a10g-tensor-core-gpus/

**Comment by hkchengrex** [comment]
What was the CPU usage?

**Comment by jingliang95** [comment]
Hi, CPU usage is around 5%.

**Comment by jingliang95** [comment]
More information: for S3, it is around 32 hours (using your default config). The speed for S3 is close to your experiments. But the speed for S0 differs **a lot** from yours. Any idea why? The reason I think of is that S0 does a lot of augmentations. What are your thoughts? Thank you

**Comment by hkchengrex** [comment]
If disabling TPS leads to speed-up it usually indicates a CPU bottleneck. Increasing num_workers helps if there are unused CPU cores laying around. Your CPU seems pretty free so I am surprised that it didn't help. Another potential reason is slow IO (i.e., disks) but I am not sure if that is the case.
