### ISSUE TITLE
Adding objects dynamically

### ISSUE THREAD

**Issue by Davidyao99** [hkchengrex/XMem#92]
Does the amount of GPU memory usage increase as the number of tracked objects increase? If so, is it possible to dynamically add and remove tracked objects while using the model in an online fashion? Interested in testing this out. Will really appreciate if some advice can be given. Thank you and amazing project!!

**Comment by hkchengrex** [comment]
1. Yes.
2. Yes but it is not implemented here. I would suggest replacing the memory data structure with a dictionary with object id as keys and memory key/value as values. Then insertion/deletion should be straightforward.

**Comment by Davidyao99** [comment]
I see, I will look into it. Another question I have is related to multi-object tracking. From the paper, most of the technical details explained seem to be in the context of single-object tracking. Could you elaborate a little on how this is extended to multi-object tracking?

Is there a set of keys, values of size C^k x N for every object in the long-term / working memory? OR perhaps, the N here now represents (THWn+Ln) instead of (THW+L) in the paper where n is the number of objects tracked?

Thank you so much for your help :))

**Comment by hkchengrex** [comment]
Keys are shared between objects while values are not, as in STCN.

**Comment by Davidyao99** [comment]
I see. You suggest using a dictionary with object id as keys and memory keys as values. Does this mean that for dynamic removal of objects, keys are no longer shared between objects?

**Comment by hkchengrex** [comment]
They don't have to but that's probably easier to implement. Alternatively, you can keep the keys in a single tensor, store pointers in the dictionary, and keep a usage count to delete unreferenced keys like smart pointers.

**Comment by Davidyao99** [comment]
I see, thank you! I think I got it to work by instead of making a dictionary for every key/value, I instead made a dictionary in memory_manager and created a kv_memory_store for every object that is being tracked.

One other thing is based on reading the code, is the hidden state in memory_manager used for the sensory memory? Does this mean that when I remove items, I have to reorder the hidden state such that the dimensions corresponding to the tracked objects remains consistent? Eg. hidden state may initially be for 100 objects. I remove object 5, so now my mask is for 99 objects. I have to remove the corresponding component of the hidden state for object 5?

**Comment by hkchengrex** [comment]
Yes; you can also convert the hidden state to a dictionary in the same way.

**Comment by Davidyao99** [comment]
Great, everything seems to be almost working. There is still one last issue that I suspect might have to do with sensory memory. I am introducing ground truth masks in every n frame. However, it seems that the very next frame does not continue smoothly from that frame. Previously when I was testing without the dictionary implementation, this did not seem to be an issue. 

This might be difficult to resolve but I was wondering where else will the order of tracked object matter? perhaps somewhere in the GRU? I noticed in match_memory in memory_manager, I made sure to return the all_readout_memory such that they are stacked in the same order as the hidden states. Is there perhaps somewhere else where such ordering might matter in the network / memory stores? Might be difficult for you to help with this one but thanks and really appreciated!

**Comment by hkchengrex** [comment]
The order should not matter if implemented correctly. It might have something to do with hidden state initialization (first zero-initialized, then updated by a "deep update").

Adding intermediate masks should improve the result as the network can adapt to appearance changes. If doing so makes the performance worse, there might be a bug in adding new memory.

**Comment by Davidyao99** [comment]
Thank you! I figured it out! I was updating my working memory every frame. Previously, I only updated working memory every time I received a ground truth intermediate mask, which led to better masks. Thanks for your help ;))

**Comment by VGrondin** [comment]
Hi @Davidyao99,
I was wondering if you would be willing to share some of your code to handle the insertion/removal of new objects without having to deal with object groups? I would use it with Segment anything Model. Best.

**Comment by hkchengrex** [comment]
@VGrondin We will release some code that might be related in the coming weeks :)

**Comment by VGrondin** [comment]
Cool! Are you releasing a new research paper or updating this repo?

**Comment by hkchengrex** [comment]
@VGrondin A new paper.

**Comment by hkchengrex** [comment]
@VGrondin https://github.com/hkchengrex/Tracking-Anything-with-DEVA 😄
