### ISSUE TITLE
Per Frame Confidence Scores during tracking

### ISSUE THREAD

**Issue by egeozguroglu** [hkchengrex/XMem#96]
Hi, is it possible to retrieve per frame confidence scores during tracking?

**Comment by hkchengrex** [comment]
You can get the mask probabilities before argmax here: https://github.com/hkchengrex/XMem/blob/083698bbb4c5ac0ffe1a8923a6c313de46169983/eval.py#L221

**Comment by hkchengrex** [comment]
I don't recall seeing that line of code. It is probably probabilities after softmax.
